# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install requires packages
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade 
          sudo apt-get -y install gcc build-essential uuid-dev iasl nasm gcc-aarch64-linux-gnu python3-distutils python3-pil python3-git gettext wine clang llvm
      - name: Build device vayu
        run: |
          ./build.sh --device vayu
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with: # Artifact name
          name: vayu
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.img
